# [CONFIG] Global category mapping rules for buildings layer
# Maps raw OSM building tags to clean categories

residential:
  - house
  - apartments
  - residential
  - detached
  - semidetached_house
  - terrace
  - bungalow
  - static_caravan

commercial:
  - office
  - retail
  - commercial
  - shop
  - supermarket
  - mall
  - warehouse
  - industrial
  - factory
  - manufacture

civic:
  - school
  - university
  - hospital
  - clinic
  - library
  - museum
  - theatre
  - cinema
  - town_hall
  - fire_station
  - police
  - courthouse
  - prison

religious:
  - church
  - cathedral
  - chapel
  - mosque
  - synagogue
  - temple
  - monastery

transport:
  - train_station
  - subway_entrance
  - bus_station
  - airport
  - hangar
  - parking
  - garage

utility:
  - utility
  - transformer_tower
  - service
  - technical
  - water_tower
  - pumping_station

agriculture:
  - farm
  - farm_auxiliary
  - barn
  - stable
  - greenhouse
  - silo

other:
  - ruins
  - construction
  - roof
  - shed
  - hut
  - cabin
  - bunker
