# [CONFIG] Global category mapping rules for cycling infrastructure layer
# Maps raw OSM cycling tags to clean categories

dedicated_cycleway:
  - cycleway

shared_path:
  - path
  - footway

on_road_infrastructure:
  - lane
  - track
  - opposite
  - opposite_lane
  - shared_lane
  - shoulder

crossing:
  - crossing

bicycle_facilities:
  - designated
  - official
  - yes

traffic_calming:
  - living_street
  - residential
