# Curitiba City Configuration
# Capital of Paraná, Brazil - Model for sustainable urban development

city:
  name: "Curitiba"
  full_name: "Curitiba, Paraná, Brazil"
  country: "Brazil"
  state: "Paraná"
  language: "pt-BR"
  timezone: "America/Sao_Paulo"
  
  # Geographic bounds [min_lon, min_lat, max_lon, max_lat]
  # Covers Curitiba metropolitan area
  bbox: [-49.4, -25.6, -49.2, -25.4]
  
  # Coordinate reference systems
  crs_storage: "EPSG:4326"            # Storage CRS (WGS84)
  crs_analysis: "EPSG:31982"          # Analysis CRS (UTM Zone 22S - Brazil)

# Data sources
data_sources:
  # OSM data source - Paraná state for comprehensive coverage
  osm_pbf: "data/raw/parana-latest.osm.pbf"
  
  # GTFS data source - Rede Integrada de Transporte (RIT)
  gtfs: "data/external/curitiba_gtfs.zip"
  
  # Administrative boundaries
  boundaries: "data/external/curitiba_boundaries.geojson"
  
  # District boundaries (Bairros)
  districts: "data/external/bairros_curitiba.geojson"
  
  # Population data by bairro
  population: "data/external/population_curitiba.csv"
  
  # BRT route network
  brt_routes: "data/external/rit_routes.geojson"
  
  # Green spaces and parks
  green_spaces: "data/external/green_spaces_curitiba.geojson"

# Processing settings
processing:
  # Memory and performance settings
  memory_limit: "4GB"
  timeout_seconds: 1800
  chunk_size: 10000
  
  # Parallel processing
  parallel_jobs: 4
  
  # Caching
  cache_results: true
  
  # Output formats
  output_formats: ["parquet", "geojson", "csv"]

# City-specific characteristics
characteristics:
  # Urban form - Curitiba has a planned grid system with radial corridors
  urban_form: "planned_grid"
  
  # Terrain - Relatively flat with gentle hills
  terrain: "flat_with_hills"
  
  # Climate - Subtropical highland climate
  climate: "subtropical_highland"
  
  # Transport systems - Famous for BRT and integrated transport
  transport_systems:
    - "brt"           # Bus Rapid Transit (RIT)
    - "bus"           # Conventional bus network
    - "bicycle"       # Cycling infrastructure
    - "walking"       # Pedestrian infrastructure
  
  # Special features - Curitiba's unique characteristics
  special_features:
    - "brt_system"        # World-famous BRT implementation
    - "green_belt"        # Environmental preservation areas
    - "linear_parks"      # Parks along watercourses
    - "planned_development" # Innovative urban planning
    - "waste_management"   # Innovative waste collection
    - "mixed_use_zoning"   # Zoning that promotes mixed development

# Analysis parameters
analysis_parameters:
  # Public transport - Focus on BRT system
  public_transport:
    high_frequency_threshold: 15      # minutes (BRT headway)
    peak_hours: ["07:00", "09:00", "17:00", "19:00"]
    access_distance: 300              # meters (walking to BRT stations)
    access_distance_cycling: 1000     # meters (cycling to BRT stations)
    
    # BRT-specific parameters
    brt:
      enabled: true
      min_frequency: 10               # minutes (BRT minimum headway)
      station_spacing: 500            # meters (typical BRT station spacing)
      dedicated_lanes: true
      tube_stations: true
  
  # Walkability - Curitiba is pedestrian-friendly
  walkability:
    poi_access_distance: 500          # meters
    intersection_buffer: 50           # meters
    sidewalk_analysis: true
    pedestrian_crossings: true
    traffic_signals: true
    
    # Curitiba-specific walkability features
    tree_coverage: true               # Famous tree-lined boulevards
    public_plazas: true               # Public squares and gathering spaces
    mixed_use_access: true            # Access to mixed-use development
  
  # Green spaces - Curitiba has extensive green infrastructure
  green_spaces:
    access_distance: 500              # meters
    min_area: 1000                   # m²
    
    # Curitiba-specific green features
    types:
      parks:
        min_area: 1000                # m²
        weight: 0.4
        include_playgrounds: true
        examples: ["Parque Barigui", "Parque Tanguá"]
      
      linear_parks:
        min_area: 500                 # m²
        weight: 0.3
        include_watercourses: true
        examples: ["Parque Linear do Rio Barigui"]
      
      green_belt:
        min_area: 10000               # m²
        weight: 0.2
        include_preservation: true
        examples: ["Parque das Nascentes"]
      
      tree_corridors:
        min_area: 100                 # m²
        weight: 0.1
        include_boulevards: true
        examples: ["Avenida Sete de Setembro"]
  
  # Cycling - Curitiba is developing cycling infrastructure
  cycling:
    dedicated_lanes: true
    shared_lanes: true
    bike_paths: true
    bike_parking: true
    
    # Curitiba-specific cycling features
    integration_with_brt: true        # Bike parking at BRT stations
    green_corridors: true             # Cycling through green areas

# Output settings
outputs:
  # Map generation
  maps:
    dpi: 300
    format: "png"
    colormap: "viridis"
    include_legend: true
    legend_position: "inside"
    include_scale_bar: true
    include_north_arrow: true
    
    # Curitiba-specific map features
    language: "pt-BR"                 # Portuguese labels
    include_brt_routes: true          # Show BRT network
    include_green_spaces: true        # Highlight green infrastructure
  
  # Report generation
  reports:
    format: "pdf"
    language: "pt-BR"                 # Portuguese reports
    include_executive_summary: true
    include_methodology: true
    include_results: true
    include_recommendations: true
    
    # Curitiba-specific report sections
    include_brt_analysis: true        # BRT system performance
    include_green_infrastructure: true # Green space assessment
    include_urban_planning: true      # Planning effectiveness
  
  # Data export
  data_export:
    formats: ["parquet", "geojson", "csv"]
    include_metadata: true
    compression: "gzip"
    include_processing_log: true
    
    # Curitiba-specific data
    include_brt_metrics: true         # BRT performance data
    include_green_metrics: true       # Green infrastructure data
    include_district_rankings: true   # Bairro performance data

# Metadata
metadata:
  # Data source information
  source: "Curitiba Municipal Government + OpenStreetMap + RIT"
  last_updated: "2024-12-19"
  coordinate_system: "WGS84 + UTM Zone 22S"
  
  # Contact information
  contact:
    organization: "Curitiba Municipal Planning Department"
    email: "planejamento@curitiba.pr.gov.br"
    website: "https://www.curitiba.pr.gov.br"
  
  # License information
  license: "Open Data License"
  license_url: "https://www.curitiba.pr.gov.br/dados-abertos"
  
  # Data quality
  quality:
    accuracy: "High"
    completeness: "Complete for urban area"
    currency: "Regular updates"
    lineage: "Official municipal data + OSM community data"

